### ISSUE TITLE
Mobile Forces - why no loaded all textures? 

### ISSUE THREAD

**Issue by gedas919** [NVIDIAGameWorks/dxvk-remix#31] opened 2023-06-18 14:19 UTC
![20230618110831_1](https://github.com/NVIDIAGameWorks/dxvk-remix/assets/135579965/7b3af29c-782a-4663-9118-c8166ed6091c)

Maybe someone can help solve this problem?

**Comment by Speedwagen** [comment] 2023-06-19 14:32
I think this is similar to the issue I am having. I think the other textures are displayed in a different render target.
https://github.com/NVIDIAGameWorks/dxvk-remix/issues/24

**Comment by NV-DM** [comment] 2023-11-01 22:13
Duplicate of https://github.com/NVIDIAGameWorks/dxvk-remix/issues/24. Closing. Thank you for your contribution.

**Closed by NV-DM** 2023-11-01 22:13 UTC
